//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace App.Ask.Properties
{
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Ask.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 drop view post_view;
        ///drop view  person_view;
        ///drop view comment_view;
        ///drop view activity_view;
        ///DROP TABLE config;
        ///DROP TABLE comment;
        ///DROP TABLE honor;
        ///DROP TABLE person;
        ///DROP TABLE post;
        ///DROP TABLE role;
        ///DROP TABLE tag;
        ///DROP TABLE topic;
        ///DROP TABLE user_honor;
        ///DROP TABLE invite_code;
        ///DROP TABLE post_tag;
        ///DROP TABLE activity;
        ///DROP TABLE favorite;
        ///DROP TABLE follow;
        ///DROP TABLE zan;
        ///drop table person_data;
        ///drop  table post_data; 的本地化字符串。
        /// </summary>
        internal static string ClearTables
        {
            get
            {
                return ResourceManager.GetString("ClearTables", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 create view post_view as
        ///select p.*,
        ///        p2.nick_name  as person_nick_name,
        ///        p2.is_delete  as person_is_delete,
        ///        p2.is_mute    as person_is_mute,
        ///        p2.avatar     as person_avatar,
        ///        t.name        as topic_name,
        ///        t.is_hide     as topic_is_hide,
        ///        t.is_announce as topic_is_announce
        ///from post as p
        ///            inner join person p2 on p2.id = p.person_id
        ///            inner join topic t on p.topic_id = t.id;
        ///
        ///create view person_view as
        ///select p.*,
        ///        p [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string createIndex
        {
            get
            {
                return ResourceManager.GetString("createIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 --创建表
        ///CREATE TABLE config(
        ///id uuid PRIMARY KEY,
        ///config_key varchar(500) not null ,
        ///config_value varchar(500) not null 
        ///);
        ///
        ///
        ///
        ///CREATE TABLE comment(
        ///id uuid PRIMARY KEY,
        ///parent_id uuid ,
        ///post_id uuid not null ,
        ///person_id uuid not null ,
        ///html_content text not null ,
        ///text_content text not null ,
        ///create_time TIMESTAMP not null ,
        ///modify_time TIMESTAMP ,
        ///is_delete boolean not null ,
        ///like_num int not null 
        ///);
        ///
        ///CREATE INDEX idx_comment_post_id on comment(post_id);
        ///CREATE INDEX idx_comment_pers [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CreateTables
        {
            get
            {
                return ResourceManager.GetString("CreateTables", resourceCulture);
            }
        }
    }
}
